directories:
    - source: "$CONFIG_DIR"
      files:
        - gtk-2.0
        - gtk-3.0
        - gtk-4.0
        - kate
        - Kvantum
        - latte
        - dolphinrc
        - katerc
        - konsolerc
        - kcminputrc
        - kdeglobals
        - kglobalshortcutsrc
        - klipperrc
        - krunnerrc
        - kscreenlockerrc
        - ksmserverrc
        - kwinrc
        - kwinrulesrc
        - plasma-org.kde.plasma.desktop-appletsrc
        - plasmarc
        - plasmashellrc
        - gtkrc
        - gtkrc-2.0
        - lattedockrc
        - breezerc
        - oxygenrc
        - lightlyrc
        - ksplashrc
        - khotkeysrc

    - source: "$SHARE_DIR"
      files:
        - plasma
        - kwin
        - konsole
        - fonts
        - color-schemes
        - aurorae
        - icons
        - wallpapers

    - source: "$HOME"
      files:
        - .fonts
        - .themes
        - .icons

    - "$HOME/Pictures/Nice Wallpapers"